import decimal
import functools
import operator
import uuid
from functools import cache
from typing import Any

from paradedb.sqlalchemy import pdb, search
from sqlalchemy import (
    CTE,
    ColumnElement,
    Select,
    case,
    cast,
    delete,
    exists,
    func,
    insert,
    literal,
    select,
    update,
    and_,
    or_,
)

from api.notes.domain import NoteOut
from api.user_asset_operations.domain import (
    UserAssetOperationData,
    DbCRUDOperationReturnData,
    UserAssetOperationsFilter,
    NettoPositionData,
    UserAssetOperationWithNotesOut, NoteFilter,
)
from api.user_assets.domain import UserAssetAggregatedData, UserAssetAggregatedPage
from database.postgres.repositories.base_repository import PostgresBaseRepository
from logic.db_models import (
    AssetOperationType,
    UserAssetOperation,
    UserAsset,
    UserAssetAddress,
    AssetTickerPrice,
    Note,
    notes_association_table,
)
from logic.repositories.user_asset_operation import BaseUserAssetOperationRepository

"""
SQL examples generated by insert_if_valid() and update_if_valid().

Both methods use a common pattern:
  1. asset_check       – verify that UserAsset exists for this user
  2. address_check     – verify that UserAssetAddress exists for this user
  3. balance_check     – current token quantity on the address (PURCHASE - SELL)
  4. balance_ok        – for SELL: qty <= balance; for PURCHASE: always TRUE
  5. insert_op/update_op – perform the DML only when all checks pass
  Final SELECT returns asset_exists, address_exists, balance, balance_ok and the operation id.

------------------------------------------------------------------------------
1. insert_if_valid() – INSERT a new operation
------------------------------------------------------------------------------

WITH asset_check AS (
    SELECT EXISTS (
        SELECT 1
        FROM user_assets
        WHERE user_assets.user_id = '7f4296f5-ba32-434e-9c18-2ad2e40b9526'
          AND user_assets.id = 82
    ) AS ok
),
address_check AS (
    SELECT EXISTS (
        SELECT 1
        FROM user_asset_addresses
        WHERE user_asset_addresses.user_id = '7f4296f5-ba32-434e-9c18-2ad2e40b9526'
          AND user_asset_addresses.id = 99
    ) AS ok
),
balance_check AS (
    SELECT COALESCE(
        SUM(
            CASE
                WHEN type = 'PURCHASE' THEN quantity
                WHEN type = 'SELL'   THEN -quantity
                ELSE 0
            END
        ), 0
    ) AS balance
    FROM user_asset_operations
    WHERE address_id = 99
      AND user_asset_id = 82
),
balance_ok AS (
    SELECT
        CASE
            WHEN CAST('SELL' AS asset_operation_type) != 'SELL' THEN TRUE
            ELSE 100 <= (SELECT balance_check.balance FROM balance_check)
        END AS ok
),
insert_op AS (
    INSERT INTO user_asset_operations (time, type, user_asset_id, quantity, unit_price, address_id)
    SELECT
        '2026-05-11 16:44:27.015309'::timestamptz AS time,
        CAST('SELL' AS asset_operation_type)       AS type,
        82                                          AS user_asset_id,
        100                                         AS quantity,
        11                                          AS unit_price,
        99                                          AS address_id
    WHERE (SELECT asset_check.ok FROM asset_check)
      AND (SELECT address_check.ok FROM address_check)
      AND (SELECT balance_ok.ok FROM balance_ok)
    RETURNING id
)
SELECT
    (SELECT asset_check.ok FROM asset_check)       AS asset_exists,
    (SELECT address_check.ok FROM address_check)   AS address_exists,
    (SELECT balance_check.balance FROM balance_check) AS balance,
    (SELECT balance_ok.ok FROM balance_ok)         AS balance_ok,
    (SELECT insert_op.id FROM insert_op)           AS op_id;

------------------------------------------------------------------------------
2. update_if_valid() – UPDATE an existing operation (id = 25)
   Note: the operation being updated is excluded from the balance calculation
   via "AND id != 25" inside balance_check.
------------------------------------------------------------------------------

WITH asset_check AS (
    SELECT EXISTS (
        SELECT 1
        FROM user_assets
        WHERE user_assets.user_id = '7f4296f5-ba32-434e-9c18-2ad2e40b9526'
          AND user_assets.id = 82
    ) AS ok
),
address_check AS (
    SELECT EXISTS (
        SELECT 1
        FROM user_asset_addresses
        WHERE user_asset_addresses.user_id = '7f4296f5-ba32-434e-9c18-2ad2e40b9526'
          AND user_asset_addresses.id = 99
    ) AS ok
),
balance_check AS (
    SELECT COALESCE(
        SUM(
            CASE
                WHEN type = 'PURCHASE' THEN quantity
                WHEN type = 'SELL'   THEN -quantity
                ELSE 0
            END
        ), 0
    ) AS balance
    FROM user_asset_operations
    WHERE address_id = 99
      AND user_asset_id = 82
      AND id != 25                                     -- exclude the row being updated
),
balance_ok AS (
    SELECT
        CASE
            WHEN CAST('SELL' AS asset_operation_type) != 'SELL' THEN TRUE
            ELSE 100 <= (SELECT balance_check.balance FROM balance_check)
        END AS ok
),
sq AS (
    SELECT
        '2026-05-11 16:44:27.015309'::timestamptz AS time,
        CAST('SELL' AS asset_operation_type)       AS type,
        82                                          AS user_asset_id,
        100                                         AS quantity,
        11                                          AS unit_price,
        99                                          AS address_id
    WHERE (SELECT asset_check.ok FROM asset_check)
      AND (SELECT address_check.ok FROM address_check)
      AND (SELECT balance_ok.ok FROM balance_ok)
),
update_op AS (
    UPDATE user_asset_operations
    SET
        time          = sq.time,
        type          = sq.type,
        user_asset_id = sq.user_asset_id,
        quantity      = sq.quantity,
        unit_price    = sq.unit_price,
        address_id    = sq.address_id
    FROM sq
    WHERE user_asset_operations.id = 25
    RETURNING user_asset_operations.id
)
SELECT
    (SELECT asset_check.ok FROM asset_check)           AS asset_exists,
    (SELECT address_check.ok FROM address_check)       AS address_exists,
    (SELECT balance_check.balance FROM balance_check)  AS balance,
    (SELECT balance_ok.ok FROM balance_ok)             AS balance_ok,
    (SELECT update_op.id FROM update_op)               AS op_id;
    
    
--------------------------------------------------------------------------------------------------------------
3 delete_if_valid

DELETE FROM user_asset_operations USING user_assets
    WHERE user_asset_operations.id = :id
        AND user_assets.id = user_asset_operations.user_asset_id
        AND user_assets.user_id = :user_id
    RETURNING user_asset_operations.id

--------------------------------------------------------------------------------------------------------------
4. get_user_asset_aggregates() – aggregated per-token stats for a user's portfolio.
   Includes a scalar correlated subquery that collects all distinct wallet names
   for each token by unnesting the wallet_name array column.

SELECT
    -- Current token quantity: PURCHASE adds, SELL subtracts
    COALESCE(SUM(CASE WHEN type = 'PURCHASE' THEN quantity ELSE -quantity END), 0::decimal) AS coin_qty_now,
    -- Number of unique addresses used for this token
    COUNT(DISTINCT address_id) AS unique_addresses_cnt,
    -- Total USDT spent on purchases
    COALESCE(SUM(CASE WHEN type = 'PURCHASE' THEN summ END), 0::decimal) AS purchased_for_usdt,
    -- Total USDT received from sells
    COALESCE(SUM(CASE WHEN type = 'SELL' THEN summ END), 0::decimal) AS sold_for_usdt,
    -- How many purchase/sell operations
    COUNT(*) FILTER (WHERE type = 'PURCHASE') AS num_purchases,
    COUNT(*) FILTER (WHERE type = 'SELL') AS num_sells,
    ua.name,
    ua.ticker_id,
    ua.id,
    -- Scalar correlated subquery: collects all distinct wallet names across
    -- every address that ever held this token. Uses UNNEST to flatten the
    -- text[] column, then ARRAY_AGG(DISTINCT) to deduplicate.
    COALESCE(
        (
            SELECT ARRAY_AGG(DISTINCT w)
            FROM user_asset_operations uao2
            JOIN user_asset_addresses uaa2 ON uaa2.id = uao2.address_id
            CROSS JOIN LATERAL UNNEST(uaa2.wallet_name) AS w
            WHERE uao2.user_asset_id = ua.id
        ),
        '{}'::text[]
    ) AS wallet_names
FROM user_asset_operations uao
JOIN user_assets ua ON uao.user_asset_id = ua.id
WHERE ua.user_id = '<uuid>'                     -- filter by user
GROUP BY ua.id, ua.name, ua.ticker_id;          -- one row per token
"""


@cache
class PostgresUserAssetOperationRepository(
    PostgresBaseRepository[UserAssetOperation],
    BaseUserAssetOperationRepository,
):
    model = UserAssetOperation

    @staticmethod
    def _build_asset_check_cte(
        user_id: uuid.UUID,
        user_asset_id: int,
    ) -> CTE:
        return (
            select(
                exists()
                .where(UserAsset.user_id == user_id, UserAsset.id == user_asset_id)
                .label("ok"),
            )
            .cte("asset_check")
        )

    @staticmethod
    def _build_address_check_cte(
        user_id: uuid.UUID,
        address_id: int,
    ) -> CTE:
        return (
            select(
                exists()
                .where(UserAssetAddress.user_id == user_id, UserAssetAddress.id == address_id)
                .label("ok"),
            )
            .cte("address_check")
        )

    @staticmethod
    def _build_balance_check_cte(
        address_id: int,
        user_asset_id: int,
        exclude_operation_id: int | None = None,
    ) -> CTE:
        stmt = select(
            func.coalesce(
                func.sum(
                    case(
                        (UserAssetOperation.type == AssetOperationType.PURCHASE, UserAssetOperation.quantity),
                        else_=-UserAssetOperation.quantity,
                    ),
                ),
                0,
            ).label("balance"),
        ).where(
            UserAssetOperation.address_id == address_id,
            UserAssetOperation.user_asset_id == user_asset_id,
        )

        if exclude_operation_id is not None:
            stmt = stmt.where(UserAssetOperation.id != exclude_operation_id)

        return stmt.cte("balance_check")

    @staticmethod
    def _build_balance_ok_cte(
        type_: AssetOperationType,
        quantity: decimal.Decimal,
        balance_check: CTE,
    ) -> CTE:
        return select(
            case(
                (
                    type_ != AssetOperationType.SELL,
                    literal(True),
                ),
                else_=(
                    select(balance_check.c.balance).scalar_subquery() >= quantity
                ),
            ).label("ok"),
        ).cte("balance_ok")

    @staticmethod
    def _build_value_columns(
        data: UserAssetOperationData,
    ) -> list[ColumnElement[Any]]:
        return [
            literal(data.time).label("time"),
            cast(literal(data.type), UserAssetOperation.type.type).label("type"),
            literal(data.user_asset_id).label("user_asset_id"),
            literal(data.quantity).label("quantity"),
            literal(data.unit_price).label("unit_price"),
            literal(data.address_id).label("address_id"),
        ]

    @staticmethod
    def _build_final_select(
        asset_check: CTE,
        address_check: CTE,
        balance_check: CTE,
        balance_ok: CTE,
        op_cte: CTE,
    ) -> Select:
        return select(
            select(asset_check.c.ok).scalar_subquery().label("asset_exists"),
            select(address_check.c.ok).scalar_subquery().label("address_exists"),
            select(balance_check.c.balance).scalar_subquery().label("balance"),
            select(balance_ok.c.ok).scalar_subquery().label("balance_ok"),
            select(op_cte.c.id).scalar_subquery().label("op_id"),
        )

    async def insert_if_valid(
        self,
        data: UserAssetOperationData,
    ) -> DbCRUDOperationReturnData:
        asset_check = self._build_asset_check_cte(data.user_id, data.user_asset_id)
        address_check = self._build_address_check_cte(data.user_id, data.address_id)

        balance_check = self._build_balance_check_cte(
            address_id=data.address_id,
            user_asset_id=data.user_asset_id,
            exclude_operation_id=None,
        )
        balance_ok = self._build_balance_ok_cte(
            type_=data.type,
            quantity=data.quantity,
            balance_check=balance_check,
        )

        values = self._build_value_columns(data)

        insert_op = (
            insert(UserAssetOperation)
            .from_select(
                [
                    UserAssetOperation.time,
                    UserAssetOperation.type,
                    UserAssetOperation.user_asset_id,
                    UserAssetOperation.quantity,
                    UserAssetOperation.unit_price,
                    UserAssetOperation.address_id,
                ],
                select(*values).where(
                    select(asset_check.c.ok).scalar_subquery(),
                    select(address_check.c.ok).scalar_subquery(),
                    select(balance_ok.c.ok).scalar_subquery(),
                ),
            )
            .returning(UserAssetOperation.id)
            .cte("insert_op")
        )

        final_stmt = self._build_final_select(asset_check, address_check, balance_check, balance_ok, insert_op)

        async with self.db.session() as session:
            row = await session.execute(final_stmt)
            await session.commit()
            asset_exists, address_exists, balance, balance_ok, inserted_id = row.one()

            return DbCRUDOperationReturnData(
                inserted_id,
                asset_exists,
                address_exists,
                balance,
                balance_ok,
            )

    async def update_if_valid(
        self,
        data: UserAssetOperationData,
    ) -> DbCRUDOperationReturnData:
        asset_check = self._build_asset_check_cte(data.user_id, data.user_asset_id)
        address_check = self._build_address_check_cte(data.user_id, data.address_id)

        balance_check = self._build_balance_check_cte(
            address_id=data.address_id,
            user_asset_id=data.user_asset_id,
            exclude_operation_id=data.id,
        )
        balance_ok = self._build_balance_ok_cte(
            type_=data.type,
            quantity=data.quantity,
            balance_check=balance_check,
        )

        values = self._build_value_columns(data)

        sq = (
            select(*values)
            .where(
                select(asset_check.c.ok).scalar_subquery(),
                select(address_check.c.ok).scalar_subquery(),
                select(balance_ok.c.ok).scalar_subquery(),
            )
            .subquery("sq")
        )

        update_op = (
            update(UserAssetOperation)
            .values(
                {
                    UserAssetOperation.time: sq.c.time,
                    UserAssetOperation.type: sq.c.type,
                    UserAssetOperation.user_asset_id: sq.c.user_asset_id,
                    UserAssetOperation.quantity: sq.c.quantity,
                    UserAssetOperation.unit_price: sq.c.unit_price,
                    UserAssetOperation.address_id: sq.c.address_id,
                },
            )
            .where(
                UserAssetOperation.id == data.id,
                sq.c.user_asset_id == UserAssetOperation.user_asset_id,
                sq.c.address_id == UserAssetOperation.address_id,
            )
            .returning(UserAssetOperation.id)
            .cte("update_op")
        )

        final_stmt = self._build_final_select(asset_check, address_check, balance_check, balance_ok, update_op)

        async with self.db.session() as session:
            row = await session.execute(final_stmt)
            await session.commit()
            asset_exists, address_exists, balance, balance_ok, updated_id = row.one()

            return DbCRUDOperationReturnData(
                updated_id,
                asset_exists,
                address_exists,
                balance,
                balance_ok,
            )

    async def delete_if_valid(self, _id: int, user_id: uuid.UUID) -> int | None:
        stmt = (
            delete(UserAssetOperation)
            .where(
                UserAssetOperation.id == _id,
                UserAsset.id == UserAssetOperation.user_asset_id,
                UserAsset.user_id == user_id,
            )
            .returning(UserAssetOperation.id)
        )

        async with self.db.session() as session:
            deleted_id = await session.scalar(stmt)
            await session.commit()

        return deleted_id

    async def netto_position(
        self,
        user_asset_id: int,
        user_id: uuid.UUID,
        op_filter: UserAssetOperationsFilter,
    ) -> NettoPositionData | None:
        """Calculate netto position metrics for a given user asset.

        Returns comprehensive position analysis including:
        total_invested, net_quantity, break_even_price,
        price_recover_50pct, current_price, unrealized_pnl,
        roi_pct, avg_purchase_price, avg_sell_price,
        current_position_value, unique_addresses_cnt,
        first_trade_at, last_trade_at, days_in_position.
        """
        # CTE with aggregated metrics from operations
        calc = (
            select(
                # total_invested: PURCHASE adds summ, SELL subtracts summ
                func.coalesce(
                    func.sum(
                        case(
                            (UserAssetOperation.type == AssetOperationType.PURCHASE, UserAssetOperation.summ),
                            else_=-UserAssetOperation.summ,
                        ),
                    ),
                    decimal.Decimal(0),
                ).label('total_invested'),
                # net_quantity: PURCHASE adds qty, SELL subtracts qty
                func.coalesce(
                    func.sum(
                        case(
                            (
                                UserAssetOperation.type == AssetOperationType.PURCHASE,
                                UserAssetOperation.quantity,
                            ),
                            else_=-UserAssetOperation.quantity,
                        ),
                    ),
                    decimal.Decimal(0),
                ).label('net_quantity'),
                # avg_purchase_price: total spent on purchases / total purchased qty
                func.coalesce(
                    func.sum(UserAssetOperation.summ).filter(
                        UserAssetOperation.type == AssetOperationType.PURCHASE,
                    ) / func.nullif(
                        func.sum(UserAssetOperation.quantity).filter(
                            UserAssetOperation.type == AssetOperationType.PURCHASE,
                        ),
                        0,
                    ),
                    decimal.Decimal(0),
                ).label('avg_purchase_price'),
                # avg_sell_price: total revenue from sells / total sold qty
                func.coalesce(
                    func.sum(UserAssetOperation.summ).filter(
                        UserAssetOperation.type == AssetOperationType.SELL,
                    ) / func.nullif(
                        func.sum(UserAssetOperation.quantity).filter(
                            UserAssetOperation.type == AssetOperationType.SELL,
                        ),
                        0,
                    ),
                    decimal.Decimal(0),
                ).label('avg_sell_price'),
                # unique_addresses_cnt: number of distinct addresses used
                func.count(UserAssetOperation.address_id.distinct()).label('unique_addresses_cnt'),
                # first_trade_at / last_trade_at: time range of operations
                func.min(UserAssetOperation.time).label('first_trade_at'),
                func.max(UserAssetOperation.time).label('last_trade_at'),
            )
            .where(UserAssetOperation.user_asset_id == user_asset_id)
        )
        
        calc = self.apply_filters(calc, op_filter).cte('calc')

        # Final SELECT: combine calc CTE with asset info and current price
        stmt = (
            select(
                calc.c.total_invested,
                calc.c.net_quantity,
                # break_even_price: price at which selling all remaining coins covers investment
                (calc.c.total_invested / func.nullif(calc.c.net_quantity, 0)).label('break_even_price'),
                # price_recover_50pct: price at which selling 50% covers all investment
                (2 * calc.c.total_invested / func.nullif(calc.c.net_quantity, 0)).label('price_recover_50pct'),
                AssetTickerPrice.price.label('current_price'),
                # unrealized_pnl: current value - total invested
                (
                    calc.c.net_quantity * AssetTickerPrice.price - calc.c.total_invested
                ).label('unrealized_pnl'),
                # roi_pct: (current_value / total_invested - 1) * 100
                (
                    (
                        calc.c.net_quantity * AssetTickerPrice.price / func.nullif(calc.c.total_invested, 0)
                        - 1
                    ) * 100
                ).label('roi_pct'),
                calc.c.avg_purchase_price,
                calc.c.avg_sell_price,
                # current_position_value: net_quantity * current_price
                (calc.c.net_quantity * AssetTickerPrice.price).label('current_position_value'),
                calc.c.unique_addresses_cnt,
                calc.c.first_trade_at,
                calc.c.last_trade_at,
                # days_in_position: now - first trade
                func.extract('day', func.now() - calc.c.first_trade_at).label('days_in_position'),
            )
            .select_from(calc)
            .join(UserAsset, UserAsset.id == user_asset_id)
            .where(
                UserAsset.user_id == user_id,
                UserAsset.id == user_asset_id,
            )
            .outerjoin(
                AssetTickerPrice, AssetTickerPrice.name == UserAsset.ticker_id,
            )
        )

        async with self.db.session() as session:
            row = await session.execute(stmt)
            result = row.one_or_none()

        if result is None:
            return None

        return NettoPositionData(*result)

    async def get_user_asset_aggregates(
        self,
        user_id: uuid.UUID,
        page_size: int,
        cursor: str | None = None,
    ) -> UserAssetAggregatedPage:
        """Aggregated per-token stats for a given user with keyset pagination.

        Uses the existing (user_id, ticker_id) unique constraint as the
        pagination cursor. Lexicographic ordering on ticker_id is natural
        for uppercase ticker symbols (BTC, ETH, SOL, ...).

        Args:
            user_id:         The user to fetch data for.
            page_size:       How many tokens to return per page.
            cursor:  Ticker ID from the previous page's last item.
                             Pass None for the first page.

        Returns:
            UserAssetAggregatedPage with items, cursor, and has_more flag.
        """
        # Inner subquery: unnest the text[] column into individual rows.
        # Using a subquery here instead of raw func.unnest() inside
        # array_agg(), because PostgreSQL forbids set-returning functions
        # inside aggregate expressions. The outer query then applies
        # array_agg(DISTINCT ...) on the result of this subquery.
        inner_unnest = (
            select(
                func.unnest(UserAssetAddress.wallet_name).label("w"),
            )
            .select_from(UserAssetOperation)
            .join(UserAssetAddress)
            .where(UserAssetOperation.user_asset_id == UserAsset.id)
            .correlate(UserAsset)
            .subquery()
        )
        wallet_names_subq = (
            select(func.array_agg(func.distinct(inner_unnest.c.w)))
            .select_from(inner_unnest)
            .scalar_subquery()
        )

        # Where clause: filter by user, and if paginating — skip past the cursor
        where_conditions = [UserAsset.user_id == user_id]
        if cursor is not None:
            where_conditions.append(UserAsset.ticker_id > cursor)

        stmt = (
            select(
                # Current token quantity: PURCHASE adds, SELL subtracts
                func.coalesce(
                    func.sum(
                        case(
                            (UserAssetOperation.type == AssetOperationType.PURCHASE, UserAssetOperation.quantity),
                            else_=-UserAssetOperation.quantity,
                        ),
                    ),
                    decimal.Decimal(0),
                ).label("coin_qty_now"),
                # Number of unique addresses used for this token
                func.count(UserAssetOperation.address_id.distinct()).label("unique_addresses_cnt"),
                # Total USDT spent on purchases
                func.coalesce(
                    func.sum(UserAssetOperation.summ).filter(UserAssetOperation.type == AssetOperationType.PURCHASE),
                    decimal.Decimal(0),
                ).label("purchased_for_usdt"),
                # Total USDT received from sells
                func.coalesce(
                    func.sum(UserAssetOperation.summ).filter(UserAssetOperation.type == AssetOperationType.SELL),
                    decimal.Decimal(0),
                ).label("sold_for_usdt"),
                # How many purchase/sell operations
                func.count("*").filter(UserAssetOperation.type == AssetOperationType.PURCHASE).label("num_purchases"),
                func.count("*").filter(UserAssetOperation.type == AssetOperationType.SELL).label("num_sells"),
                UserAsset.name,
                UserAsset.ticker_id,
                UserAsset.id,
                # Scalar correlated subquery for wallet names
                func.coalesce(
                    wallet_names_subq,
                    literal([]),
                ).label("wallet_names"),
            )
            .select_from(UserAssetOperation)
            .join(UserAsset)
            .where(*where_conditions)
            .group_by(UserAsset.id, UserAsset.name, UserAsset.ticker_id)
            .order_by(UserAsset.ticker_id)
            .limit(page_size + 1)  # fetch one extra row to detect next page
        )

        async with self.db.session() as session:
            rows = await session.execute(stmt)

        all_items = [UserAssetAggregatedData(*row) for row in rows]

        # Determine if there is a next page
        if len(all_items) > page_size:
            has_more = True
            all_items = all_items[:page_size]
        else:
            has_more = False

        # last_ticker_id: ticker_id of the last returned item, or None if empty
        last_ticker_id = all_items[-1].ticker_id if all_items else None

        return UserAssetAggregatedPage(
            items=all_items,
            cursor=last_ticker_id,
            has_more=has_more,
        )

    def get_user_asset_operations_stmt(
        self,
        user_asset_id: int,
        user_id: uuid.UUID,
        filters: UserAssetOperationsFilter,
    ) -> Select:
        """Build a SELECT statement for user asset operations with address details.

        Corresponding SQL:
            SELECT
                uao.id,
                uao.type,
                uao.quantity,
                uao.unit_price,
                uao.summ,
                uao.time,
                uaa.wallet_name,
                uaa.public_key
            FROM user_asset_operations uao
            JOIN user_asset_addresses uaa ON uao.address_id = uaa.id
            WHERE uao.user_asset_id = :user_asset_id
              AND uaa.user_id = :user_id
            ORDER BY uao.time DESC
        """
        stmt = select(
                self.model.id,
                self.model.type,
                self.model.quantity,
                self.model.unit_price,
                self.model.summ,
                self.model.time,
                UserAssetAddress.wallet_name,
                UserAssetAddress.public_key,
            ).select_from(
                self.model,
            ).join(
                self.model.address,
            ).where(
                self.model.user_asset_id == user_asset_id,
                UserAssetAddress.user_id == user_id,
            ).order_by(
                self.model.time.desc(),
            )

        return self.apply_filters(stmt, filters)


    async def get_by_notes(
        self,
        user_id: uuid.UUID,
        op_filter: UserAssetOperationsFilter,
        notes: list[str],
        note_filter: NoteFilter,
        distance: int,
    ) -> list[UserAssetOperationWithNotesOut]:

        #  words in each search term are connected with AND logic (new bicycle = new and bicycle)
        #  multiple search terms are joined with OR logic ((new and bicycle) or (old and motorcycle)
        search_criteria = functools.reduce(
            or_,
            (search.match_all(Note.note, note, distance=distance) for note in notes),
        )

        all_notes_cte = (
            select(
                notes_association_table.c.op_id,
                func.jsonb_agg(
                    func.jsonb_build_object(
                        'id', Note.id,
                        'note', Note.note,
                        'created_at', Note.created_at,
                        'snippet', pdb.snippet(Note.note, max_num_chars=75),
                        'score', pdb.score(Note.id),
                    ),
                ).label('notes'),
                #  this is for future sorting by score
                (func.max(pdb.score(Note.id)) + func.ln(func.count('*'))).label('score'),
            )
            .select_from(
                notes_association_table,
            )
            .join(
                Note,
                and_(
                    Note.id == notes_association_table.c.note_id,
                    search_criteria,
                )
            )
            .group_by(
                notes_association_table.c.op_id,
            ).cte('all_notes')
        )

        # all_notes_cte = self.apply_filters(all_notes_cte, note_filter).cte('all_notes')

        stmt = (
            select(
                self.model,
                all_notes_cte.c.score,
                all_notes_cte.c.notes,
            )
            .select_from(
                self.model,
            )
            .join(
                UserAsset,
                and_(
                    UserAsset.id == self.model.user_asset_id,
                    UserAsset.user_id == user_id,
                )
            )
            .join(
                all_notes_cte,
                all_notes_cte.c.op_id == self.model.id,
            )
            .order_by(
                all_notes_cte.c.score.desc().nulls_last(),
                self.model.time.desc(),
            )
        )
        stmt = self.apply_filters(stmt, op_filter)

        async with self.db.session() as session:
            rows = await session.execute(stmt)

        return [
            UserAssetOperationWithNotesOut(
                **model_instance.as_fields_dict(),
                score=score,
                notes=[NoteOut(**note) for note in sorted(notes, key=operator.itemgetter('score'), reverse=True)],
            )
            for model_instance, score, notes in rows.all()
        ]

# todo citus
