apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          image: backend-api
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              port: 8000
              path: '/'
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: backend-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
