services:
  backend-api:
    build: .
#    ports:
#      - "8000:8000"
    expose:
      - '8000'
    environment:
      GRANIAN_RELOAD: 1
      GRANIAN_WORKERS_LIFETIME: 60
      GRANIAN_METRICS_ENABLED: 1
      UV_NO_DEV: 1
      ALEMBIC_CONFIG: alembic/alembic.ini
      PGHOSTADDR: postgres
      DEBUG: ${DEBUG:-1}
    networks: [ ledger-network ]
    healthcheck:
      test: ["CMD-SHELL", "./aux/docker/healthcheck/backend_healthcheck.sh"]
      interval: 10s
      timeout: 2s
      retries: 2
      start_period: 1s
    restart: unless-stopped
    depends_on:
      - postgres
      - caddy
#      postgres:
#        condition: service_healthy
    volumes:
      - ./alembic:/app/alembic:z
      - .:/app:Z
    develop:
      watch:
        - action: sync+restart
          path: ./docker-compose.yaml
          target: ./app/docker-compose.yaml

#  ---

  postgres:
    image: postgres:18
    container_name: my_postgres
    restart: unless-stopped
    profiles: [main]
    command: [
      "postgres",
      "-c", "shared_buffers=8GB",
      "-c", "effective_cache_size=24GB",
      "-c", "work_mem=64MB",
      "-c", "maintenance_work_mem=2GB",
      "-c", "wal_buffers=64MB",
      "-c", "huge_pages=try",
      "-c", "max_connections=200",
      "-c", "superuser_reserved_connections=3",
      "-c", "wal_level=replica",
      "-c", "max_wal_size=4GB",
      "-c", "min_wal_size=1GB",
      "-c", "wal_compression=on",
      "-c", "synchronous_commit=on",
      "-c", "checkpoint_timeout=15min",
      "-c", "checkpoint_completion_target=0.9",
      "-c", "bgwriter_delay=200ms",
      "-c", "bgwriter_lru_maxpages=100",
      "-c", "bgwriter_lru_multiplier=2.0",
      "-c", "random_page_cost=1.1",
      "-c", "effective_io_concurrency=200",
      "-c", "default_statistics_target=100",
      "-c", "max_parallel_workers_per_gather=2",
      "-c", "max_parallel_workers=8",
      "-c", "max_parallel_maintenance_workers=2",
      "-c", "autovacuum=on",
      "-c", "autovacuum_max_workers=3",
      "-c", "autovacuum_vacuum_scale_factor=0.1",
      "-c", "autovacuum_analyze_scale_factor=0.05",
      "-c", "autovacuum_vacuum_cost_delay=2ms",
      "-c", "autovacuum_vacuum_cost_limit=1000",
      "-c", "log_filename='postgresql-%Y-%m-%d.log'",
      "-c", "log_min_duration_statement=1000",
      "-c", "log_checkpoints=on",
      "-c", "log_lock_waits=on",
      "-c", "log_temp_files=0",
      "-c", "log_autovacuum_min_duration=0",
      "-c", "log_line_prefix='%m [%p] %q%u@%d '",
      "-c", "password_encryption=scram-sha-256",
      "-c", "idle_in_transaction_session_timeout=1min",
      "-c", "idle_session_timeout=5min"
    ]
    env_file: secrets/postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      [ ledger-network ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $PGDATABASE -U $PGUSER || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s
    stop_grace_period: 120s

  #  ---

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    profiles: [main]
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9000:9000"
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
    depends_on:
      - postgres
    networks:
      [ ledger-network ]
    env_file:
      - ./secrets/keycloak/.env
    restart: unless-stopped
    healthcheck:
      test: [
        "CMD-SHELL",
        "{ printf 'HEAD /health/ready HTTP/1.0\r\n\r\n' >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/9000 || exit 1"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

    #  ---

  caddy:
    image: caddy:2.11-alpine
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./aux/caddy:/etc/caddy:ro
      - ./site:/srv:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      [ ledger-network ]
    profiles: [main]

  #  ---

networks:
    ledger-network:
      driver: bridge

volumes:
  pg_patroni1:
  pg_patroni2:
  postgres_data:
  keycloak_data:
  caddy_data:
  caddy_config:
