#!/usr/bin/env just --justfile

set dotenv-filename := "secrets/just/.env"
set lazy

backend_name := 'backend-api'

default:
   just --list

alias up := up-dev
alias down := down-dev
alias pytest := test

#  start container, start without temporal -- just up main, start few profiles -- just up profile1,profile2,...
[group('docker')]
up-dev *profiles="*": && down-dev
    COMPOSE_PROFILES={{profiles}} docker compose up --watch

#  force recreate container
[group('docker')]
force-recreate:
    docker compose --profile main up --watch --force-recreate

#  stop container
[group('docker')]
down-dev *profiles="*":
    COMPOSE_PROFILES={{profiles}} docker compose down --remove-orphans

#  build container
[group('docker')]
build:
    docker compose build

# restart ledger-api service
[group('docker')]
restart name="backend-api":
    docker compose restart {{name}}

#  remove dangling volumes
[group('docker')]
rm-volumes:
    docker volume rm $(docker volume ls -qf dangling=true)

#  make alemic autogenerated migration. just makemigrations {{message}}
[group('alembic')]
makemigrations message:
    docker compose exec {{backend_name}} uv run alembic revision --autogenerate -m "{{message}}"

# push alembic migration into db
[group('alembic')]
migrate where='head':
   docker compose exec {{backend_name}} uv run alembic upgrade {{where}}

# remove last migration from db
[group('alembic')]
downgrade where='-1':
    docker compose exec {{backend_name}} uv run alembic downgrade {{where}}

# open keycloak web ui
[group('keycloak')]
keycloak:
    xdg-open http://localhost:8080/admin/master/console/#/test

# reloads caddy web server config file
[group('caddy')]
caddy-reload:
    docker compose --profile main kill  -sUSR1 caddy

# run tests
[arg('skip-alembic', help='skip alembic migration before testrun')]
[group('pytest')]
test path='' skip-alembic='--skip-alembic' *flags:
    docker compose exec {{backend_name}} bash -c "uv run pytest {{path}} {{skip-alembic}} {{flags}}"

# open api docs
[group('api')]
api-docs:
    nohup xdg-open https://localhost:8000/docs >/dev/null 2>&1 &

# open temporal web ui
[group('temporal')]
temporal-ui:
    nohup xdg-open 'http://localhost:8081/' >/dev/null 2>&1 &

# build temporal worker
[group('temporal')]
[working-directory: 'etl']
temporal-worker-rebuild:
    docker compose build --no-cache temporal-worker

# HAProxy web UI (admin, 1q2w3e)
[group('haproxy')]
haproxy-ui:
    nohup xdg-open http://localhost:8404/haproxy?stats >/dev/null 2>&1 &

# HAProxy config hot reload
[group('haproxy')]
haproxy-reload:
    docker compose --profile main kill -s HUP haproxy

# Minio web ui
[group('minio')]
minio-ui:
    nohup xdg-open http://127.0.0.1:9001/browser >/dev/null 2>&1 &

# render error-description templates with jinja
[group('static')]
render-html:
    docker compose exec {{backend_name}} bash -c "uv run aux/html_templates/error_description_templates.py"

# uv run something
[group('aux')]
run path:
    docker compose exec {{backend_name}} bash -c "uv run {{path}}"


