#!/usr/bin/env just --justfile

set dotenv-filename := "secrets/just/.env"
set lazy

backend_name := 'backend-api'

default:
   just --list

alias up := up-dev
alias down := down-dev
alias pytest := test

#  start container
[group('docker')]
up-dev profile="main":
    docker compose --profile {{profile}} up --watch

#  force recreate container
[group('docker')]
force-recreate:
    docker compose --profile main up --watch --force-recreate

#  stop container
[group('docker')]
down-dev profile="main":
    docker compose --profile {{profile}} down

#  build container
[group('docker')]
build:
    docker compose build

#  make alemic autogenerated migration. just makemigrations {{message}}
[group('alembic')]
makemigrations message:
    docker compose exec {{backend_name}} uv run alembic revision --autogenerate -m "{{message}}"

# push alembic migration into db
[group('alembic')]
migrate where='head':
   docker compose exec {{backend_name}} uv run alembic upgrade {{where}}

# remove last migration from db
[group('alembic')]
downgrade where='-1':
    docker compose exec {{backend_name}} uv run alembic downgrade {{where}}

# open keycloak web ui
[group('keycloak')]
keycloak:
    xdg-open http://localhost:8080/admin/master/console/#/test

#  reloads caddy web server config file
[group('caddy')]
caddy-reload:
    docker compose --profile main kill  -sUSR1 caddy

#  run tests
[arg('skip-alembic', help='skip alembic migration before testrun')]
[group('pytest')]
test path='' skip-alembic='--skip-alembic' *flags:
    docker compose exec {{backend_name}} bash -c "uv run pytest {{skip-alembic}} {{path}} {{flags}}"

# open api docs
[group('api')]
api-docs:
    xdg-open https://localhost:8000/docs

# open temporal web ui
[group('temporal')]
temporal-ui:
    nohup xdg-open 'http://localhost:8081/' >/dev/null 2>&1 &

#  build temporal worker
[group('temporal')]
[working-directory: 'etl']
temporal-worker-build:
    docker build  -t temporal-worker .

