#!/usr/bin/env just --justfile

set dotenv-filename := "secrets/just/.env"

default: up-dev

alias up := up-dev
alias down := down-dev

profile := ""
message := ""

#  start container
up-dev:
    docker compose  up --watch --remove-orphans

#  stop container
down-dev:
    docker compose down

#  build container
build:
    docker compose build

#  make alemic autogenerated migration. just message=test makemigrations
[positional-arguments]
makemigrations:
    uv run alembic revision --autogenerate -m "{{message}}"
