[project]
name = "ledger"
version = "0.22.8"
description = "Keeos track on you crypto assets"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "asyncstdlib>=3.13.1",
    "granian[pname,reload,rloop,uvloop]>=2.7.1",
    "litestar[opentelemetry,sqlalchemy,standard]>=2.20.0",
    "opentelemetry-exporter-otlp>=1.40.0",
    "opentelemetry-exporter-otlp-proto-grpc>=1.40.0",
    "opentelemetry-instrumentation-logging>=0.51b0",
    "opentelemetry-instrumentation-sqlalchemy>=0.52b0",
    "opentelemetry-distro>=0.51b0",
    "opentelemetry-instrumentation-httpx>=0.52b0",
    "pydantic-settings>=2.13.1",
    "pynng>=0.9.0",
    "python-keycloak>=7.1.1",
    "sqlalchemy[asyncio]>=2.0.46",
    "structlog>=25.5.0",
    "temporalio>=1.26.0",
    "polars>=1.40.1",
    "opentelemetry-instrumentation-asyncio>=0.52b0",
    "sqlalchemy-paradedb>=0.6.0",
]

[dependency-groups]
dev = [
    "httpx-sse>=0.4.3",
    "ipython>=9.10.0",
    "pydevd-pycharm~=253.30387.173",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "pytest-env>=1.6.0",
    "pytest-httpx>=0.36.0",
    "pytest-randomly>=4.0.1",
    "pytest-xdist[psutil]>=3.8.0",
    "remote-pdb>=2.1.0",
    "ty>=0.0.35",
    "web-pdb>=1.6.3",
]

[tool.pytest.ini_options]
console_output_style = "count"
filterwarnings = [
    "ignore::UserWarning",
    "ignore:Core Pydantic V1 functionality",
]
asyncio_mode = "auto"
addopts = "-vv --pytest-env-verbose"

[tool.uv]
exclude-newer = "7 days"

[tool.pytest_env]
PGDATABASE = "ledger-db-test"
POOL_CLASS = "null"
PGHOSTADDR = "postgres"
OTEL_SDK_DISABLED = "true"

[tool.uv.workspace]
members = [
    "etl",
]

[tool.ty.src]
exclude = ["alembic/", ".venv/", ".cache/"]
