"""Asset ticker price delete

Revision ID: 04a0851f68c1
Revises: 755f6f063c89
Create Date: 2026-05-20 06:57:33.945522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04a0851f68c1'
down_revision: Union[str, Sequence[str], None] = '755f6f063c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_updated_at'), table_name='asset_tickers_price')
    op.drop_table('asset_tickers_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_tickers_price',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('price > 0::numeric', name=op.f('positive_price_check')),
    sa.ForeignKeyConstraint(['name'], ['asset_tickers.name'], name=op.f('asset_tickers_price_name_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name', name=op.f('asset_tickers_price_pkey'))
    )
    op.create_index(op.f('ix_updated_at'), 'asset_tickers_price', ['updated_at'], unique=False)
    # ### end Alembic commands ###
