"""change UserAsset field name

Revision ID: 0b3fbc6c2df7
Revises: 937d0a828551
Create Date: 2026-04-20 10:09:50.043154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3fbc6c2df7'
down_revision: Union[str, Sequence[str], None] = '937d0a828551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_assets', sa.Column('ticker_id', sa.String(length=10), nullable=False))
    op.drop_constraint(op.f('user_assets_user_id_ticker_key'), 'user_assets', type_='unique')
    op.create_unique_constraint(None, 'user_assets', ['user_id', 'ticker_id'])
    op.drop_constraint(op.f('user_assets_ticker_fkey'), 'user_assets', type_='foreignkey')
    op.create_foreign_key(None, 'user_assets', 'asset_tickers', ['ticker_id'], ['name'], ondelete='RESTRICT')
    op.drop_column('user_assets', 'ticker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_assets', sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_assets', type_='foreignkey')
    op.create_foreign_key(op.f('user_assets_ticker_fkey'), 'user_assets', 'asset_tickers', ['ticker'], ['name'], ondelete='RESTRICT')
    op.drop_constraint(None, 'user_assets', type_='unique')
    op.create_unique_constraint(op.f('user_assets_user_id_ticker_key'), 'user_assets', ['user_id', 'ticker'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_assets', 'ticker_id')
    # ### end Alembic commands ###
