"""add saved_att into asset_ticker_price

Revision ID: 1230b7cefa57
Revises: 89aa332b60e6
Create Date: 2026-05-25 12:13:09.673525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1230b7cefa57'
down_revision: Union[str, Sequence[str], None] = '89aa332b60e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_tickers_price', sa.Column('saved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_tickers_price', 'saved_at')
    # ### end Alembic commands ###
