"""create notes

Revision ID: 365d80987b82
Revises: 1f8a888854fe
Create Date: 2026-06-10 12:09:20.555644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '365d80987b82'
down_revision: Union[str, Sequence[str], None] = '1f8a888854fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes_association_table',
    sa.Column('op_id', sa.BIGINT(), nullable=False),
    sa.Column('note_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['op_id'], ['user_asset_operations.id'], ),
    sa.PrimaryKeyConstraint('op_id', 'note_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes_association_table')
    op.drop_table('notes')
    # ### end Alembic commands ###
