"""Index for Note

Revision ID: 368333a9526d
Revises: 365d80987b82
Create Date: 2026-06-11 14:12:56.127249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368333a9526d'
down_revision: Union[str, Sequence[str], None] = '365d80987b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_bm25_index('notes_search_idx', 'notes', ['id', "((note)::pdb.unicode_words('stemmer=russian','ascii_folding=true','stopwords_language=russian','trim=true'))", 'created_at'], key_field='id', table_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_bm25_index('notes_search_idx', if_exists=True, schema='public')
    # ### end Alembic commands ###
