"""fix addess_id

Revision ID: 686d31883ada
Revises: 9fe5158feba1
Create Date: 2026-04-10 09:53:27.508457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '686d31883ada'
down_revision: Union[str, Sequence[str], None] = '9fe5158feba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_asset_operations', sa.Column('address_id', sa.BIGINT(), nullable=False))
    op.drop_constraint(op.f('user_asset_operations_address_fkey'), 'user_asset_operations', type_='foreignkey')
    op.create_foreign_key(None, 'user_asset_operations', 'user_asset_addresses', ['address_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('user_asset_operations', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_asset_operations', sa.Column('address', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_asset_operations', type_='foreignkey')
    op.create_foreign_key(op.f('user_asset_operations_address_fkey'), 'user_asset_operations', 'user_asset_addresses', ['address'], ['id'], ondelete='RESTRICT')
    op.drop_column('user_asset_operations', 'address_id')
    # ### end Alembic commands ###
