"""Notes index

Revision ID: 9304ddd838ca
Revises: 365d80987b82
Create Date: 2026-06-10 12:37:27.479688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9304ddd838ca'
down_revision: Union[str, Sequence[str], None] = '365d80987b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_bm25_index('notes_search_idx', 'notes', ['note', 'created_at'], key_field='id', table_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_bm25_index('notes_search_idx', if_exists=True, schema='public')
    # ### end Alembic commands ###
