"""user_asset_addr wallet name ARRAY

Revision ID: 937d0a828551
Revises: eaa92d6b7045
Create Date: 2026-04-14 14:48:19.475382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '937d0a828551'
down_revision: Union[str, Sequence[str], None] = 'eaa92d6b7045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_asset_addresses', 'wallet_name',
                existing_type=sa.TEXT(),
                type_=postgresql.ARRAY(sa.String(length=50)),
                postgresql_using='wallet_name::character varying(50)[]',
                existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_asset_addresses', 'wallet_name',
               existing_type=postgresql.ARRAY(sa.String(length=50)),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
