"""add o delete into userassetoperations

Revision ID: 94b62d944b15
Revises: 368333a9526d
Create Date: 2026-06-15 09:39:36.863692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b62d944b15'
down_revision: Union[str, Sequence[str], None] = '368333a9526d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notes_association_table_note_id_fkey'), 'notes_association_table', type_='foreignkey')
    op.drop_constraint(op.f('notes_association_table_op_id_fkey'), 'notes_association_table', type_='foreignkey')
    op.create_foreign_key(None, 'notes_association_table', 'user_asset_operations', ['op_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notes_association_table', 'notes', ['note_id'], ['id'], ondelete='CASCADE')
    op.drop_bm25_index('notes_search_idx', if_exists=True, schema='public', table_name='notes', expressions=['id', "(note::pdb.unicode_words('stemmer=russian', 'ascii_folding=true', 'stopwords_language=russian', 'trim=true'))", 'created_at'], key_field='id')
    op.create_bm25_index('notes_search_idx', 'notes', ['id', "((note)::pdb.unicode_words('stemmer=russian','ascii_folding=true','stopwords_language=russian','trim=true'))", 'created_at'], key_field='id', table_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_bm25_index('notes_search_idx', if_exists=True, schema='public')
    op.create_bm25_index('notes_search_idx', 'notes', ['id', "(note::pdb.unicode_words('stemmer=russian', 'ascii_folding=true', 'stopwords_language=russian', 'trim=true'))", 'created_at'], key_field='id', table_schema='public')
    op.drop_constraint(None, 'notes_association_table', type_='foreignkey')
    op.drop_constraint(None, 'notes_association_table', type_='foreignkey')
    op.create_foreign_key(op.f('notes_association_table_op_id_fkey'), 'notes_association_table', 'user_asset_operations', ['op_id'], ['id'])
    op.create_foreign_key(op.f('notes_association_table_note_id_fkey'), 'notes_association_table', 'notes', ['note_id'], ['id'])
    # ### end Alembic commands ###
