"""Asset ticker price add id

Revision ID: 9c8a92703bce
Revises: 755f6f063c89
Create Date: 2026-05-20 06:46:26.870377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8a92703bce'
down_revision: Union[str, Sequence[str], None] = '755f6f063c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_tickers_price', sa.Column('id', sa.BIGINT(), sa.Identity(always=True), nullable=False))
    op.create_unique_constraint('name_uq', 'asset_tickers_price', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('name_uq', 'asset_tickers_price', type_='unique')
    op.drop_column('asset_tickers_price', 'id')
    # ### end Alembic commands ###
