"""create asset models

Revision ID: 9fe5158feba1
Revises: bf2583e2ee33
Create Date: 2026-04-09 14:51:55.482388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fe5158feba1'
down_revision: Union[str, Sequence[str], None] = 'bf2583e2ee33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_tickers',
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.CheckConstraint('name = upper(name)', name='name_is_upper'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user_asset_addresses',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('public_key', sa.TEXT(), nullable=False),
    sa.Column('wallet_name', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_assets',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['asset_tickers.name'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker')
    )
    op.create_table('user_asset_operations',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('type', postgresql.ENUM('PURCHASE', 'SELL', name='asset_operation_type'), nullable=False),
    sa.Column('user_asset_id', sa.BIGINT(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('unit_price', sa.Numeric(), nullable=False),
    sa.Column('summ', sa.Numeric(), sa.Computed('unit_price * quantity', ), nullable=False),
    sa.Column('address', sa.BIGINT(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='asset_qty_gt_0'),
    sa.CheckConstraint('unit_price > 0', name='unit_price_gt_0'),
    sa.ForeignKeyConstraint(['address'], ['user_asset_addresses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_asset_id'], ['user_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_asset_id', 'user_asset_operations', ['user_asset_id'], unique=False)
    op.add_column('user', sa.Column('email', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    op.drop_index('ix_user_asset_id', table_name='user_asset_operations')
    op.drop_table('user_asset_operations')
    op.drop_table('user_assets')
    op.drop_table('user_asset_addresses')
    op.drop_table('asset_tickers')
    # ### end Alembic commands ###
