"""create asset price model

Revision ID: d213fe43ae09
Revises: edd2384e0ab2
Create Date: 2026-05-19 10:56:57.007747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd213fe43ae09'
down_revision: Union[str, Sequence[str], None] = 'edd2384e0ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_tickers_price',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price > 0', name='positive_price_check'),
    sa.ForeignKeyConstraint(['name'], ['asset_tickers.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index('ix_updated_at', 'asset_tickers_price', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_updated_at', table_name='asset_tickers_price')
    op.drop_table('asset_tickers_price')
    # ### end Alembic commands ###
