"""user_asset_addr pubkey unique

Revision ID: eaa92d6b7045
Revises: 686d31883ada
Create Date: 2026-04-14 14:42:31.704058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaa92d6b7045'
down_revision: Union[str, Sequence[str], None] = '686d31883ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_asset_addresses', ['public_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_asset_addresses', type_='unique')
    # ### end Alembic commands ###
