"""add user_id into user_asset_address

Revision ID: edd2384e0ab2
Revises: b459efb7fc98
Create Date: 2026-05-06 11:58:29.196615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd2384e0ab2'
down_revision: Union[str, Sequence[str], None] = 'b459efb7fc98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_asset_addresses', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('user_asset_addresses_public_key_key'), 'user_asset_addresses', type_='unique')
    op.create_unique_constraint('user_key_uq', 'user_asset_addresses', ['user_id', 'public_key'])
    op.drop_constraint(op.f('user_assets_user_id_ticker_id_key'), 'user_assets', type_='unique')
    op.create_unique_constraint('user_asset_uq', 'user_assets', ['user_id', 'ticker_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_asset_uq', 'user_assets', type_='unique')
    op.create_unique_constraint(op.f('user_assets_user_id_ticker_id_key'), 'user_assets', ['user_id', 'ticker_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('user_key_uq', 'user_asset_addresses', type_='unique')
    op.create_unique_constraint(op.f('user_asset_addresses_public_key_key'), 'user_asset_addresses', ['public_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_asset_addresses', 'user_id')
    # ### end Alembic commands ###
