import abc
import asyncio
import contextlib
from functools import cache
from typing import TYPE_CHECKING, Coroutine

import pynng
import structlog
import msgspec

from config import settings
from interservice.domain import (
    PeerDiscoveryMessage,
    Header,
    MessageSubject,
    PeerDiscoveryBody, messages_types, SurveyMessage, SurveyBody,
)

if TYPE_CHECKING:
    from interservice.worker import Node
    from interservice.domain import Message

log = structlog.get_logger()

class AbstractNNGHandler(abc.ABC):
    def __init__(self, node: Node) -> None:
        self.node = node
        self.log = log.bind(name=self.node.name)

    async def send_message(self, message: Message) -> None:
        await self.node.sock.asend(msgspec.msgpack.encode(message))
        self.node.seen_messages.add(message.header.id)

    def create_nonblocking_task(self, awaitable: Coroutine) -> None:
        task = asyncio.create_task(awaitable)
        self.node._running_tasks.add(task)
        task.add_done_callback(self.node._running_tasks.discard)

    @abc.abstractmethod
    async def process_message(self, message: messages_types) -> None:
        pass

@cache
class SurveyHandler(AbstractNNGHandler):

    async def respondent(self) -> None:
        await self.log.ainfo('Starting survey responder', addr=settings.NNG_SURVEY_ADDR)
        with pynng.Respondent0(
                dial=settings.NNG_SURVEY_ADDR,
                block_on_dial=False
        ) as respondent:
            await asyncio.sleep(settings.NNG_INIT_TIME_INTERVAL)
            while not self.node.stop_event.is_set():
                    await respondent.arecv_msg()
                    await self.log.ainfo('Got survey request')
                    message = SurveyMessage(
                        header=Header(
                            from_addr=self.node.local_addr,
                            subject=MessageSubject.SURVEY,
                        ),
                        body=SurveyBody(
                            status='OK',
                        )
                    )
                    await respondent.asend(msgspec.msgpack.encode(message))
                    await self.log.ainfo('Sent message to surveyor', mesage=message)

    def start_survey_respondent(self) -> None:
        self.create_nonblocking_task(self.respondent())

    async def process_message(self, message: messages_types) -> None:
       pass


@cache
class PeerDiscoveryHandler(AbstractNNGHandler):

    # noinspection PyProtectedMember
    async def process_message(self, message: PeerDiscoveryMessage) -> None:
        new_peers = message.body.peers -  self.node.peers  # have new incoming peers
        if new_peers:
            self.node.peers |= new_peers
            await self.log.ainfo('New received peers', new_peers=new_peers)

            for peer in new_peers:
                if peer not in {self.node.local_addr, settings.NNG_BASE_ENTRYPOINT_ADR}:
                    self.node.sock.dial(peer)

            self.create_nonblocking_task(self.send_peers())
            await self.log.ainfo(
                'Sending all know peer to everyone',
                peers=self.node.peers,
            )
        else:
            await self.log.ainfo(
                'We know all these peers already. Not gonna resend them',
                node_peers = self.node.peers,
                incomming_peers = message.body.peers,
            )

    async def send_peers(self):
        if self.node.peers:
            message = PeerDiscoveryMessage(
                header=Header(
                    from_addr=self.node.local_addr,
                    subject=MessageSubject.PEERDISCOVERY,
                    #  id autogenerated here !!!
                ),
                body=PeerDiscoveryBody(
                    peers=self.node.peers,
                )
            )
            await self.send_message(message)
            await self.log.ainfo('sending message', message=message)
        else:
            await self.log.awarning('no peers, skipping send')